config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  resources :user do
    get "/analysis", to: "analysis#index"
    get 'analysis/new'
    post 'analysis/new', to: 'analysis#create'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/analysis.rb
class Analysis < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_one :analysis
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  before_action :get_user

  def new
    @analysis = @user.analyses.build
  end

  def show
    @analysis = Analysis.find(params[:id])
  end

  def create
    @analysis = @user.analyses.build(analysis_params)
    if @analysis.save
      render('pages/welcome')
    else
      render('pages/welcome')
    end
  end

  def edit
    @analysis = Analysis.find(params[:id])
  end

  private
  def analysis_params
    params.permit(:field1, :field2, :bins_data, :user_id)
  end

  def get_user
    @user = User.find(current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/analysis_helper.rb
module AnalysisHelper
  def calculate
    num1 = @analysis

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/analysis/new.html.erb
<%= @user.id %>

<%= form_with(model: @analyses, local: true) do |f| %>


  <%= f.label :field1 %>
  <%= f.number_field :field1 %>

  <%= f.label :field2 %>
  <%= f.number_field :field2%>

  <%= f.label :bins_data %>
  <%= f.number_field :bins_data %>

  <%= f.submit %>

<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div id="navbar">
      <% if signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Add analysis', user_analysis_new_path(current_user.id) %></li>
        </ul>
      <% end %>

      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
          <li><span><%= current_user.email %></span></li>
          <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecyclingProject1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= debug(params) if Rails.env.development? %>
  <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/pages/welcome.html.erb
Welcome to the prototype